- lib/method/PACMethod_xfreerdp.pm
- lib/pac_conn
As discussed in #153 here is the promised PR in 2 separate commits. One adds support to use X11::GUITest and the other adds a new setting in freerdp method to set /dynamic-resolution as user wishes.
> Add dynamic resolution and X11::GUITest method to calculate embed window size properly

- lib/method/PACMethod_xfreerdp.pm
- lib/pac_conn
Added 32 bpp option for xfreerdp method.
> Method xfreerdp: add 32 bpp

- lib/PACUtils.pm
- lib/pac_conn
fix for https://github.com/asbru-cm/asbru-cm/issues/173
> Enabled RSA Authentication via MOSH protocol

- CODING_STANDARD.md
I have a lot to learn it took me more than 2 hours to be able to only commit one single file, I had to delete the fork and clone everything again.
Here is the code standard, in a different pull will send the first change to asbru-cm
> CODING STANDARDt added

- CODING_STANDARD.md
- asbru-cm
Version with just reformatting, no other changes. It does not creates warnings of any kind or side effects.
Will have to finish reformatting and study very well afterwards how to pass the $CFG_DIR variable to all modules in a way that does not creates warnings.
> Gtk3format asbru-cm

- lib/PACCluster.pm
- lib/PACMain.pm
Proposal fix to #133 using utf8 icons
> Utf8 test (#133)

- lib/PACPCC.pm
Fix issue #98 
Replicate code from PACTerminal.pm, open cluster in windows
Added code standard
> better window placement on explode

- asbru-cm
- lib/PACCluster.pm
- lib/PACConfig.pm
- lib/PACEdit.pm
- lib/PACGlobalVarEntry.pm
- lib/PACKeePass.pm
- lib/PACMain.pm
- lib/PACPCC.pm
- lib/PACPipe.pm
- lib/PACScreenshots.pm
- lib/PACScripts.pm
- lib/PACStatistics.pm
- lib/PACTerminal.pm
- lib/PACTray.pm
- lib/PACTrayUnity.pm
- lib/PACUtils.pm
- lib/edit/PACExecEntry.pm
- lib/edit/PACExpectEntry.pm
- lib/edit/PACMethod.pm
- lib/edit/PACPrePostEntry.pm
- lib/edit/PACTermOpts.pm
- lib/edit/PACVarEntry.pm
- lib/pac_conn
This is the migration to utf8 encoding, I tested as much as I could, hope I did not forget something.
Scripts window
Main Window and tree
About
License
Preferences
Cluster Management
SSh terminals not affected
Find
Control <C>
Terminal configurations, user, password with unicode characters
Delete warnings
Rename
Cloning
Terminal Connections
Find in tree
Favourites
History
Clusters
Saving sessions with UTF8 characters
pac.yml
RDP Session
> Utf8 migration

- lib/PACMain.pm
Fixes problem of group names shown incorrectly on tray right click.
Guess there was some merge error because the groups name was created 3 times
> Fix layout

- lib/PACMain.pm
- res/asbru.glade
> Shrink preferences

- lib/PACMain.pm
- lib/PACTerminal.pm
- lib/PACUtils.pm
Added option to right clic menus on : terminal and connections.
Connections
Terminal
> added feature #295 copy password, passphrase from terminal, connections

- lib/PACCluster.pm
- lib/PACMain.pm
- lib/pac_conn
Fixes spoted by @merikz on #317
> revised unless statements, caused regressions

- lib/PACCluster.pm
> fixed regression removing unless from eq to ne

- lib/PACTerminal.pm
Fixes issue #304 , added cluster commit to remote global commands
> added cluster commit, #304

- lib/PACTerminal.pm
Added validation if users configured to confirm a command, otherwise would be transmitted to clustered terminals even if user decided not to cancel the command.
Had to homologate the return values in `sub _execute`, the function was returning true and false inconsistently.
> added execute cluster commit on confirmed if confirmation was required

- lib/PACTerminal.pm
Fix regression tabbed terminals not showing
> fixed regression tabbed terminals

- lib/PACTerminal.pm
- lib/pac_conn
Fix #373 back ported to master, just the minimum need it for this to work on main branch.
> retry on timeout

- lib/PACTerminal.pm
- lib/pac_conn
> improved restart logic on exit, removed sleep

- lib/PACTerminal.pm
Ported back to master fix bug reported on comment of closed issue #266
> fix find bug

- doc/Managing/Clusters.md
- doc/Manual/Preferences/Preferences.md
Fixed more typos, added more some notes
This will be all for today.
> more typos fixed

- doc/Manual/Preferences/KeePassXC.md
Fixed some typos in documentation
> KeePass Manual 2

- doc/Manual/Preferences/MainOptions.md
Update documentation for 2 new themes
> Docs documented new themes

- doc/Manual/Substitutions.md
- mkdocs.yml
Documenting the use of masks, internal variables variables, etc.
> Docs masks

- mkdocs.yml
Added index link to new article about expect
> Docs added missing link to new article

- doc/Manual/Preferences/MainOptions.md
- doc/Manual/Preferences/SytemTrayExtensions.md
This is a basic page for session extensions to get a system tray
> Docs added gnome shell extensions page

- doc/Manual/Connections/SSH_Terminal.md
- doc/Manual/Preferences/GlobalVariables.md
- doc/Manual/Preferences/MainOptions.md
- doc/Manual/QuickStart.md
- doc/Manual/Substitutions.md
- lib/PACEdit.pm
Fixed as many typos and grammar errors as could find on this pass.
> Docs typos 2

- doc/Contributing/index.md
- doc/General/sensitive-info-notice.md
- doc/General/senvitive-info-notice.md
- mkdocs.yml
Addedd notes from https://github.com/asbru-cm/asbru-cm/issues/563
> [Doc] Create sensitive-info-notice.md (#1)

- asbru-cm
- utils/asbru2pac.pl
- utils/asbru_confirm.pl
Before merge #515 
We should prepare master to be able to downgrade, and publish a version that can downgrade from the upcoming config migration.
> downgrade config dir migration to homologate all the code

- doc/Manual/Connections/RDP.md
- doc/Manual/Connections/SSH.md
- doc/Manual/Connections/SSH_Terminal.md
- mkdocs.yml
Connection , general information was taken outside from ssh menu and a submenu with the detail for each individual methods created.
Reorganized the information about connections, a general information section and individual connection sections.
> reorganize main menu and connections information

- lib/edit/PACExpectEntry.pm
@gfrenoy 
Fix #564 
Another small fix if you still want to squash some bugs into 6.2
> disable scroll over spin buttons in expect fix564

- lib/PACTerminal.pm
- lib/asbru_conn
Fix #588 
Test terminal exists.
Under some conditions the terminal might not be available.
> verify terminal exists before hiding

- doc/General/Installation.md
Correct typo in installation docs
> [Doc] - Correct typo in installation docs

- lib/PACUtils.pm
Fix to a regression when cleaning up terminal escape sequences.
add new lines when needed
> Fix regression logcleanup

- lib/PACKeyBindings.pm
- lib/PACTerminal.pm
- lib/PACUtils.pm
Review available options for copy-pasting in Ásbrú.
See #673
> Copy and paste cleanup

- lib/PACConfig.pm
- lib/PACUtils.pm
This is the pull request you have asked for in https://github.com/asbru-cm/asbru-cm/issues/718.
> Add 'env GDK_BACKEND=x11' to generated .desktop files

- lib/PACMain.pm
Signed-off-by: Syco <alberto.rinaudo+dino@gmail.com>
> update vte_feed_child detection

- lib/method/PACMethod_cu.pm
> Change max baud rate for using above 1 Mbps on serial(using cu)

- .travis.yml
add ubuntu hirsute (21.04) support. Fix #818
> Add 21.04 support in .travis.yml

- doc/General/Installation.md
Instructions for Gentoo added to the installation documents. Tried on my system with the following specs:
- Kernel: 5.10.61
- CPU: i7-6700HQ @ 2.60GHz
- Perl 5.34.0
- XFCE4
- systemd
If needed I can create fresh Gentoo in VM but it will take time.
> [Doc] - Gentoo instructions added to the installation docs

- README.md
- doc/General/Installation.md
Updated the docs to clarify instructions for running Asbru-CM on Windows since Xming is only required if you are not using WSLg
> Update docs on running Asbru-CM in Windows

- dist/appimage-raw/Dockerfile
- dist/appimage-raw/container_make_appimage.sh
Fixes #1038 specifically for AppImages.
> Tweak AppImage builder to pin some dependencies and add libappindicator dependency

- README.md
These instructions are much easier than using https://github.com/SegiH/Asbru-CM-Runner
> Update README.md with installation instructions for modern WSL with GUI support

- lib/PACMain.pm
I find useful to have the forwarding ports information on the connection tooltip
> Add info about forwarding ports to the SSH connection tooltip
