lib/PACEdit.pm
res/pac.glade

When Authentication is set to Manual in the "Edit Connection" dialogue, the "Expect" tab is disabled.
As a newcomer I didn't realize that it was the Manual setting that disabled it, I just wanted Expect automation even if the password was not stored in the connection settings.
In fact the meaning of "Manual" means that all automation is turned off, which is perfectly sensible when you think about it.
This patch makes the connection between Manual authentication and the disabled expect tab visible to the user by not only changing the "sensitive" setting of the tab (greying it out), but also setting the tool-tip of the tab when authentication mode is changed.

[Usability] Add tooltip to "Edit" -> "Expect" when disabled

---

lib/PACConfig.pm
lib/PACEdit.pm
lib/PACMain.pm
lib/PACTerminal.pm
lib/PACUtils.pm
lib/edit/PACExecEntry.pm
lib/edit/PACExpectEntry.pm
lib/edit/PACPrePostEntry.pm
lib/pac_conn

This fixes Issue #28.
Technically the problem was that: 
- The {txt} hash key was not referenced when replacing user variables
As the User Variables have been broken in PAC since forever it seems, I guess people do not use it.
Here's how I use it:
Create a template connection, with values as <V:0>, <V:1> wherever unique values are needed, such as ip-address, jump hosts, proxies and user name. Then just copy the connection and change all the connection unique values on the User Variables tab, instead of hunting down the different places that needs to be changed.
https://sourceforge.net/p/pacmanager/bugs/249/
Issue https://github.com/asbru-cm/asbru-cm/issues/28

[Bugfix] - User variables doesn't work

---

lib/PACTerminal.pm

I've revisited the section of code in PACTerminal.pm handling key-combinations in a terminal window.
asbru-cm now only swallows key-strokes it really uses and passes the others to the underlying terminal widget.
E.g. there is a plugin called "dircycle" for oh-my-zsh which allows cycling through recently visited directories with <ctrl>+<shift>+<leftarrow>/<rightarrow>. This was not possible prior to this patch.
While I was already there I also reformatted the code a little bit (indentations, newlines, etc.) to make it more readable and more consistent.

Don't swallow key-accelerators which are not used by asbru

---

res/asbru_bash_completion

The "have" function in bash-completion is deprecated. Indeed, using this results in completions not working.
See the [Gentoo Wiki](https://wiki.gentoo.org/wiki/Bash/Installing_completion_files) for example.

Removed deprecated "have" function

---

lib/PACConfig.pm
lib/PACTerminal.pm
lib/PACUtils.pm
res/pac.glade
res/pac.yml

Hello,
I changed how the separator in split panels is set and managed.
1. On split panels creation the separator is now set in the middle, instead of being closer to the left side.
2. There's a new menu item to reposition the separator in the middle after the window is resized.
3. There's also a new option in the global settings to force the separator to stay in the middle when the window is resized.
There's one thing I'm not sure about:
```perl
$$self{_SPLIT_VPANE} -> set_position( ( ( $vertical ? $y : $x ) / 2 ) - 7 );
$$self{_SPLIT_VPANE} -> set_position( ( ( $$self{_SPLIT_VERTICAL} ? $y : $x ) / 2 ) - 7 );
```
that " - 7" is there to compensate the width of the separator itself, so that when I do "tput cols" on both terminals they return the same number of columns.
But I guess that on …

update split panes separator handling

---

lib/PACTerminal.pm
lib/method/PACMethod_rdesktop.pm
lib/method/PACMethod_xfreerdp.pm
lib/pac_conn

This PR will merge my latest patches on RDP methods. Quick changelog:
- Both methods have now a new free text box to add any option not implemented in Ásbrú
- Fixed rdesktop width size when X11:GUITest is used (it adds 2 pixels in width, don't know why)
- Added "-K: keep window manager key bindings" as a new button in rdesktop (very useful)
- Removed rdesktop percent size, it's no longer supported upstream, so I left only: fullscreen, embed and fixed size
- Fixed some typos and improved some tooltips
- Fixed percent size in xfreerdp, regex was wrong
As always, feel free to comment and request any explanations you need... I will be on vacation a couple of weeks, so maybe if a Perl guru is reading this can review and improve the code. I tried to be correct and think as simple as I can to …

Improving RDP methods

---

lib/PACTerminal.pm

Fix annoying bug where clipboard gets lost after copy using the mouse selection on terminal
The problem is the function gets called when text is selected and deselected, if you select text and keep it selected, you can shift insert. But if the focus on the selected text gets lost, then the clipboard gets a blank text and you loose your clipboard data.
Now the clipboard is persistent as long as no new selection is made.

fix copy with mouse selection gets lost sometimes

---

lib/PACMain.pm

Fails on group names, that do not have title property.
In groups will display the group message instead.

Fix regression

---

.gitignore
lib/PACConfig.pm

Added additional option to Export Settings to allow exporting debugin information.
This will allow to import users data without personal information and help debugging when the problem is related to users settings. Many times I have seen that some combination of settings trigger bugs that we are not aware of.
When we import the settings it will look like this
This has help me recently to find some bugs that were related to setting configurations.
In addition at the end of the file I add environment variables that would help to know better the user environment.
This is a first proposal, I would like that people tests that the export process really removes personal data and that no confidential information is published by mistake.
So we add more cleaning code if necessary. 
The file is a …

Proposal Export debug information

---

lib/PACMain.pm

When opening the About dialog this was written on stderr:
Gtk-Message: 20:58:38.409: GtkDialog mapped without a transient parent.
This is discouraged.
--
I can see that this PR has a small side effect in that the dialog is not destroyed as it was before. But I guess that doesn't matter, since the show_about_dialog() seems to be the recommended way by [gnome](https://developer.gnome.org/gtk3/stable/GtkAboutDialog.html#gtk-show-about-dialog), while the previous way with $dialog->run() is mentioned as "It is also possible to show a GtkAboutDialog like any other GtkDialog, e.g. using gtk_dialog_run()"

Remove GTK-Message:GtkDialog mapped without a transient parent. (#312)

---

lib/PACTerminal.pm

Fixing regression in f7a0efc1, where "unless (expr)" idiom was
replaced with "if (! expr)". However the precedence of operator !
is higher than the negation produced by the unless statement.
Replacing with "if (not expr)" fixes this, however this
commit only changes it where is actually matters.

[gtk3] regression from removal of "unless" (fixes #314)

---

lib/PACPCC.pm

Was "Power Cluser Controller"
Now "Power Cluster Controller"

Fix spelling in banner of "Power Cluster Controller"

---

lib/PACMain.pm

Fix #386 
Show / Hide Connection list as the button bar in Info Tab, when autohide connection list option is selected.

show hidden connection list on info tab selected

---

doc/Manual/Preferences/MainOptions.md
doc/Manual/QuickStart.md

Update documentation with warnings about system tray and gnome-shell

Docs add warning about system tray on gnome-shell

---

lib/asbru_conn

Add a warning when logs can not be opened so user can check settings and directory permissions
Fix #569

added warning unable to open session log

---

lib/PACTerminal.pm

cluster terminals, take all vertical size available when exploding window terminals.

Cluster terminals

---

lib/PACMain.pm
lib/PACScreenshots.pm
lib/PACStatistics.pm

Fix #581 
The problem happens with left or right panel position. Right panel is more affected by the bug.
The largest problem came from the renaming of the Reset statistics button.
I left the button with a fixed width. And rearranged the messages to be clearer and have the same amount of lines so it would not cause the same jumping effect, vertically if the number of lines changes .
The problem arises when the connection panel is resized to squeeze the tabs panel to its minimum. If you leave no space for the statistics time connection to grow or contract you would get a small jump. Because of the resizing of that panel.
The new design will stop the large changes seen in the original bug report. But I could not find a way to control the resize, or wrapping to avoided the small changes …

Fix #581 redesigned statistics to avoid jumps

---

lib/PACTerminal.pm

Another bug fix for tabbed windows.
When option "change main window title with terminal name is set"
It works for the Terminal Window and main Ásbru window
But does not work for the Detached Tabs Window
This change makes it work in all 3 cases.
This could be added to 6.2

set window title in detached tab

---

lib/PACEdit.pm

If you edit any connection (new or existing one), and change the method, the newly selected specific method options are not visible until you close the edit window and reopen again.

fix change method, properties not visible

---

lib/PACTerminal.pm

Fix #502 
The order of events creates a 1 core cpu 100% usage for window terminals.
Moved the window destruction after removing all connections, sockets, watch events, etc.

Fix #502 Destroy windows after full disconnection

---

lib/PACKeePass.pm
lib/PACTerminal.pm

Modifications for #694 
I can not tell if this affects #694, but something changed in the way environment variables are passed or moved in mint20, or this is an undetected bug.
If the keepass password is set in asbru, it would be asked any way.

reset environment keepassword if not set and available

---

doc/General/Installation.md

I have added Windows 10 instructions at the top of docs/General/Installation.md
I felt that the Windows 10 section should be at the top of the document because Linux users will be more likely to know that they need to scroll down to find their distro instructions but Windows 10 instructions should be more prominent at the top.
I would also suggest adding this to the Asbru-CM wiki

Add win10 instructions to docs

---

lib/PACTerminal.pm

Regarding #502 
I could stop the sysread errors and the high CPU, by commenting the lines that close the socket when a disconnection is issued.
The high cpu and sysread errors on closed file handle, are due to the sockets being closed when other parts still try to read from it.
I have not seen other side effects on the rest of the application by not closing the socket during a disconnect. I could not see oprhaned sockets or some other error introduced by this.
In ubuntu 18.3
As much as I try to follow the code I could not come up with a clear understanding of when the socket creates a high cpu. There are cases where it never happens others where it does randomly.
So you could give it a test and if you think this does not creates other unseen problems by me, it should fix #502 .

do not close socket on disconnect only at the time of a full stop

---

doc/Manual/Connections/SSH.md
doc/Manual/Substitutions.md
lib/PACEdit.pm
lib/PACMain.pm
lib/PACTerminal.pm
lib/PACUtils.pm
lib/asbru_conn
lib/edit/PACExecEntry.pm
lib/edit/PACExpectEntry.pm
lib/edit/PACPrePostEntry.pm
res/asbru.glade
utils/asbru_from_superputty.py

Following the previous epiphany on pull request #762 I've reimplemented this function as a local command.
The functionality I had intended is still the same, and I'm happy with both implementations, but I think this way it integrates better with what's already there.
Just as an example, the command I use with this new variable is: `bash -c 'TMP_HOME="$(mktemp -d)"; HOME="${TMP_HOME}" /usr/bin/chromium --incognito --proxy-server="socks5://localhost:<SOCKS5_PORT>" --proxy-bypass-list="<-loopback>"; rm -Rf "${TMP_HOME}"'`
Thanks

Add random socks5 port to connctions and add related variable to use in local commands

---

README.md

yaourt has been abandoned for several years now. It lacks many features and has many security issues.
I changed the mention so now it mentions [the manual install process](https://wiki.archlinux.org/index.php/Arch_User_Repository#Installing_and_upgrading_packages). I do not believe that any AUR helper should be promoted. It is up to user which one they want to use.
Also changed line so it says that the instructions are for pacman-based distros. This is because pacman contains the makepkg tool.

Do not mention yaourt

---

lib/PACTerminal.pm

When connected in ssh connections show **in status bar** the configured SSH Port Forwardings (Local, Remote or Dynamic).
Tested in clustered or unclustered windows, in SSH or not SSH connections.

:bug: Show ssh port forwarding when connected in status bar (#742)

---

lib/PACConfig.pm
lib/PACTerminal.pm
res/asbru.glade

Add options in preferences to:
- Show port forwarding information in status bar
If yes:
- Use full names (Local Forwarding, Remote Forwarding, Dynamic Forwarding)
- Use abreviatures (-L, -R, -D)

Add options in preferences to show port forwarding (full or short) in statusbar (#742)

---

lib/PACScripts.pm
lib/PACUtils.pm
lib/asbru_conn

Hi,
I have a problem with the detection of xfreerdp, for some reason https://github.com/asbru-cm/asbru-cm/blob/master/lib/PACUtils.pm#L443-L446 doesn't work for me.
But because I find the way `which` is used very ugly and inconsistent, I've decided to change all of them with `system("") eq 0`.
This way the variables `my $PERL`, `my $xfreerdp`, `my $xtightvncviewer`, etc.. now contain a value already sanitized that can be used as is.

remove all embedded which checks and replace them with system

---

doc/General/Redistribution.md
lib/PACMain.pm
mkdocs.yml

Added some code to import configurations on the first start (or when the configuration is otherwise absent) from file `$RealBin/vendor/asbru-conf-default-overrides.yml`, if it exists.
More reasoning behind the feature can be seen in [the new documentation section](https://github.com/henry701/asbru-cm/blob/loki-feat-vendor-defaults/doc/General/Redistribution.md).
Unlike [the original PR](https://github.com/asbru-cm/asbru-cm/pull/848), this does not include any additional dependencies, because there is no need to merge with existing configuration items when there are no existing configuration items in the first place (starting Ásbrú without preexisting configuration).

[Feat] Vendor default configuration overrides

---

lib/PACMain.pm
lib/PACTrayUnity.pm

New pull request against 'loki' branch.
As I said before, I'm not an expert in Perl or in GTK so change everything you need. This patch re-enables Tray Icon in my Unity Desktop, and works for me. That's all.
Regards.

Re-enable Unity tray icon in GTK3

---

lib/asbru_conn

fix `Use of '“' is deprecated as a string delimiter at /opt/asbru/lib/asbru_conn`

fix delimiter

---

lib/PACScripts.pm

A little script deletion fix.
================
Problem: The selected(s) scripts deletion was not working.
Before the change:
----------------------
and of course the scripts was not deleted
After the change
-------------------
No error raised and selected script deleted

fix: delete script was not working

---

lib/PACTerminal.pm

Like most other Tab-based terminals or text editors, there should be a "close other tabs" button, to close all terminals except for the one I clicked.
I've already achieve this feature, and didn't make too much change. Please have a look at it for review.

Add "close other terminals" button
